SCALE_FACTOR = 4
TABLE_COLOUR = (255.0, 255.0, 255.0)
TABLE_LENGTH = 198 * SCALE_FACTOR
TABLE_HEIGHT = 99 * SCALE_FACTOR
CORNER_POCKET_WIDTH = 11.4 * SCALE_FACTOR
CENTRAL_POCKET_WIDTH = 12.7 * SCALE_FACTOR
CORNER_POCKET_DEPTH = 9.53 * SCALE_FACTOR
CENTRAL_POCKET_DEPTH = 7.78 * SCALE_FACTOR

CENTRAL_POCKET_ANGLE = 15

WINDOW_LENGTH = TABLE_LENGTH + 200
WINDOW_HEIGHT = TABLE_HEIGHT + 200

BASE_RADIUS = 5.7 / 2